### ISSUE TITLE
User Auth

### ISSUE THREAD

**Issue by briceyokoyama** [briceyokoyama/Notspotify#2]
# User Auth

## Functionality

- [x] The main button with logo should link to `/`
- [x] Has working demo login
- [x] Smooth, bug free navigation

### Before Login

- [x] The `/login` page should not display a link to `Log In`. Same for `/signup`
- [x] Going to a random route `/#/oweiniouewbrviuwebv` should redirect or display a 404 page
- [x] Errors should display for both `/signup` and `/login`.
- [x] Errors should clear when moving between `/signup` and `/login`.
- [x] Can sign up a user
- [x] Can sign in as a user
- [x] Can log out a user
- [x] Can't sign up with the same username/email
- [x] Pressing enter after filling out the session form should use the form data, not the demo user

### After Login

- [x] Should not be able to visit `/login` or `/signup`
- [x] Should be able to refresh the page and still be logged in

## Style

- [x] The site should look exactly like the actual site
- [x] All relevant elements should have `cursor: pointer` on hover
- [x] When errors are displayed, most elements should not move around the page (particularly input boxes)
- [x] Remove Redux logger and all console.log()'s from production

## Seeds
- [x] Adequate and appropriate seeds

**Comment by ronilbhatia** [comment]
Overall good job! Especially getting login that works with username or email - impressive! Also in the future you can feel free to check off the boxes above and I will uncheck any that I have requested changes on.

Right now when if I try to signup using an email or username that is already taken the app crashes. You need to make sure to properly catch these errors and display them on the front-end. This is the biggest thing to improve, the rest are mostly stylistic comments.

![Screen Shot 2019-05-02 at 4 38 40 PM](https://user-images.githubusercontent.com/32026924/57113479-9db43400-6cf9-11e9-84c5-ee51df95e921.png)
![Screen Shot 2019-05-02 at 4 38 41 PM](https://user-images.githubusercontent.com/32026924/57113480-9db43400-6cf9-11e9-8786-a752b66f9653.png)

1. Need some padding on the sides of your navbar to look more like Spotify's.

![Screen Shot 2019-05-02 at 4 40 01 PM](https://user-images.githubusercontent.com/32026924/57115412-b4f81f00-6d03-11e9-9b94-934bfea82cc0.png)
![Screen Shot 2019-05-02 at 4 40 02 PM](https://user-images.githubusercontent.com/32026924/57115413-b4f81f00-6d03-11e9-8ca4-b979a3dbb09f.png)

2. The error rendering could be more clean. Ideally it would be the same as Spotify's where you have specific error's rendering for each field (you would accomplish this by returning an errors hash instead of an array, and displaying the specific errors for each field underneath - i.e. `errors.email` or `errors.password`). At the least, make the errors render a bit nicer and in red font, with less font weight.
3. You need a link to login from the signup page, and vice versa. Try to match Spotify's styling on the 'Already have an account? Log In' you see at the bottom of the session form.
4. Input boxes are a bit small compared to theirs, and your placeholder text should have a greater font-weight.

Overall good job! Just clear the above, as well as all of the unchecked checkboxes above and this MVP can be closed!

**Comment by briceyokoyama** [comment]
Was able to fix the issue of the app crashing when signing up duplicate users. Tried my best to match the style of the Spotify website.

**Comment by ronilbhatia** [comment]
Sweet, good job fixing that stuff! Looks like the bug is gone when signing up with a username/email that is already taken. Just a couple things:
1. I think you might have actually added too much margin to the navbar - I would cut the amount in half. Now it's so close to the center, that if I were to make the width of the screen smaller everything sort of collapses on everything else, which would not play well on mobile. Error rendering looks good too, good job getting the specific errors! The only other thing I'd ask here is to justify the text to the left

**Comment by briceyokoyama** [comment]
Made a few adjustments per the comments above.

**Comment by ronilbhatia** [comment]
Looks great - closing this out!
